### ISSUE TITLE
Project won't compile // Missing 2 library2 ( IniParser; IniParser.Model)

### ISSUE THREAD

**Issue by astromiester1** [rrskybox/TSX-Configuration-Reader#1]
Here is the library needed as they are not included in the project.

using IniParser;
using IniParser.Model;

Error	CS0246	The type or namespace name 'IniParser' could not be found (are you missing a using directive or an assembly reference?)	TSXConfigurationReader	C:\Users\Owner\Downloads\TSX-Configuration-Reader-master\TSXConfigurationReader\FormConfigurationReader.cs	1	Active

**Comment by rrskybox** [comment]
IniParser is a helpful little library I found in a NuGet -- Ini-Parser by Ricardo Hernandez.  Just search and load it in the VS Menu: Tools -> NuGet Package Manager -> Manage NuGet Package Manager for Solution...

I'll add a comment in the code accordingly.  Should have done it earlier, of course.

**Comment by rrskybox** [comment]
Comment added to code for Ini-Parser Nu-Get.
